services:
  twitter-bot:
    build: ./twitter-bot/
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - "database"
      - "mockup-api"
      - "neural-network"
  neural-network:
    build: ./neural-network/
    ports:
      - "10081:8081"
  database:
    build: ./database/
    volumes:
      - database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '13306:3306'
  public-api:
    build: ./public-api/
    ports:
      - "10080:8080"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - "database"
  mockup-api:
    image: mockoon/cli:latest
    ports:
      - "10090:10090"
    volumes:
      - ./mockup-api.json:/data
    command: -d data -i 0 -p 10090
    


volumes:
  database:
