services:
  twitter-bot:
    build: ./twitter-bot/
    environment:
      - AUTH_TOKENS=${AUTH_TOKENS}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - "database"
  neural-network:
    build: ./neural-network/
    ports:
      - "10081:8081"
  database:
    build: ./database/
    volumes:
      - database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '13306:3306'
  public-api:
    build: ./public-api/
    ports:
      - "10080:8080"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}


volumes:
  database:
