apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: "bot-database"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: database
          image: ghcr.io/raporpe/axolobot-database:v0.4
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: database-vol
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: axolobot
      volumes:
        - name: database-vol
          persistentVolumeClaim:
            claimName: database-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
