apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-bot
  template:
    metadata:
      labels:
        app: twitter-bot
    spec:
      containers:
        - name: twitter-bot
          image: ghcr.io/raporpe/axolobot-twitter-bot:v0.2
          env:
            - name: AUTH_TOKENS
              valueFrom:
                secretKeyRef:
                  key: AUTH_TOKENS
                  name: axolobot
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: axolobot
