name: Actions after push
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v1
        with:
          version: "v1.21.5"

      - name: Install kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/admin.conf

      - name: Set the kubeconfig path
        run: sudo chown $(id -u):$(id -g) $HOME/admin.conf && export KUBECONFIG=$HOME/admin.conf

      - name: Get the version
        id: version
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Log in to the GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: raporpe
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for the neural network
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./neural-network
          push: true
          tags: ghcr.io/raporpe/axolobot-neural-network:${{ env.RELEASE_VERSION }}

      - name: Build and push Docker image for the twitter bot
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./twitter-bot
          push: true
          tags: ghcr.io/raporpe/axolobot-twitter-bot:${{ env.RELEASE_VERSION }}

      - name: Deploy new neural network image to kubernetes
        run: kubectl --kubeconfig $HOME/admin.conf set image deployment/axolobot neural-network=ghcr.io/raporpe/axolobot-neural-network:${{ env.RELEASE_VERSION }}

      - name: Deploy new twitter bot image to kubernetes
        run: kubectl --kubeconfig $HOME/admin.conf set image deployment/axolobot twitter-bot=ghcr.io/raporpe/axolobot-twitter-bot:${{ env.RELEASE_VERSION }}
